spring.application.name=order-service
server.port=${ORDER_SERVICE_PORT:8083}

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/kisan_order_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root@123}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:KisanConnectSuperSecretKeyForFarmers2026!@KisanConnect}

# Business Configuration
app.commission.rate=${COMMISSION_RATE:0.05}
