spring.application.name=product-service
server.port=${PRODUCT_SERVICE_PORT:8082}

# Eureka Client
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8761/eureka/}

# MySQL Configuration
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/kisan_product_db?createDatabaseIfNotExist=true}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:root@123}
spring.datasource.driverClassName=com.mysql.cj.jdbc.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# JWT Configuration
jwt.secret=${JWT_SECRET:KisanConnectSuperSecretKeyForFarmers2026!@KisanConnect}

# File Upload Configuration
app.upload.dir=${UPLOAD_DIR:uploads/images}
